name: Update README

on:
  schedule:
    - cron: '30 5,11,17,23 * * *'
  workflow_dispatch:

jobs:
  update-recent-activity:
    runs-on: ubuntu-latest
    name: Update recent activity
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update README'
          MAX_LINES: 5
  
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://xiangnorth.com/atom.xml"
          
  update-waka:
    name: Update this repo's README with waka
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_6_months
          SHOW_TOTAL: true
          
  update-snake:
    name: Update this repo's README snake
    runs-on: ubuntu-latest
    steps:
      - name: generate snake
        uses: Platane/snk@v2.0.0-rc.2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: push snake to the output
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
