name: Update README

on:
  schedule:
    - cron: '30 5,13,21 * * *'
  workflow_dispatch:

jobs:
  update-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update README'
          MAX_LINES: 5
      - name: update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://xiangnorth.com/atom.xml"
          
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake
        uses: Platane/snk@v2.0.0-rc.2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: push snake to the output
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
